// Code generated by ent, DO NOT EDIT.

package migrate

import (
	"entgo.io/ent/dialect/sql/schema"
	"entgo.io/ent/schema/field"
)

var (
	// EventsColumns holds the columns for the "events" table.
	EventsColumns = []*schema.Column{
		{Name: "id", Type: field.TypeString},
		{Name: "aggregate_id", Type: field.TypeString},
		{Name: "version", Type: field.TypeString},
		{Name: "creator", Type: field.TypeString},
		{Name: "type", Type: field.TypeString},
		{Name: "aggregate_type", Type: field.TypeString},
		{Name: "org_id", Type: field.TypeString},
		{Name: "instance_id", Type: field.TypeString},
		{Name: "metadata", Type: field.TypeBytes, Nullable: true},
		{Name: "data", Type: field.TypeBytes, Nullable: true},
		{Name: "sequence", Type: field.TypeUint64},
		{Name: "previous_aggregate_sequence", Type: field.TypeUint64},
		{Name: "previous_aggregate_type_sequence", Type: field.TypeUint64},
		{Name: "service", Type: field.TypeString},
		{Name: "create_time", Type: field.TypeTime},
	}
	// EventsTable holds the schema information for the "events" table.
	EventsTable = &schema.Table{
		Name:       "events",
		Columns:    EventsColumns,
		PrimaryKey: []*schema.Column{EventsColumns[0]},
	}
	// Tables holds all the tables in the schema.
	Tables = []*schema.Table{
		EventsTable,
	}
)

func init() {
}
