// Code generated by ent, DO NOT EDIT.

package do

import (
	"context"
	"errors"
	"fmt"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/galaxyobe/go-ddd/pkg/domain/eventsouring/repository/do/event"
	"github.com/galaxyobe/go-ddd/pkg/domain/eventsouring/repository/do/predicate"
	"github.com/galaxyobe/go-ddd/pkg/types"
)

// EventUpdate is the builder for updating Event entities.
type EventUpdate struct {
	config
	hooks    []Hook
	mutation *EventMutation
}

// Where appends a list predicates to the EventUpdate builder.
func (eu *EventUpdate) Where(ps ...predicate.Event) *EventUpdate {
	eu.mutation.Where(ps...)
	return eu
}

// SetAggregateID sets the "aggregate_id" field.
func (eu *EventUpdate) SetAggregateID(t types.UUID) *EventUpdate {
	eu.mutation.SetAggregateID(t)
	return eu
}

// SetOrgID sets the "org_id" field.
func (eu *EventUpdate) SetOrgID(t types.UUID) *EventUpdate {
	eu.mutation.SetOrgID(t)
	return eu
}

// SetInstanceID sets the "instance_id" field.
func (eu *EventUpdate) SetInstanceID(t types.UUID) *EventUpdate {
	eu.mutation.SetInstanceID(t)
	return eu
}

// SetVersion sets the "version" field.
func (eu *EventUpdate) SetVersion(t types.Version) *EventUpdate {
	eu.mutation.SetVersion(t)
	return eu
}

// SetCreator sets the "creator" field.
func (eu *EventUpdate) SetCreator(t types.UUID) *EventUpdate {
	eu.mutation.SetCreator(t)
	return eu
}

// Mutation returns the EventMutation object of the builder.
func (eu *EventUpdate) Mutation() *EventMutation {
	return eu.mutation
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (eu *EventUpdate) Save(ctx context.Context) (int, error) {
	var (
		err      error
		affected int
	)
	if len(eu.hooks) == 0 {
		if err = eu.check(); err != nil {
			return 0, err
		}
		affected, err = eu.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = eu.check(); err != nil {
				return 0, err
			}
			eu.mutation = mutation
			affected, err = eu.sqlSave(ctx)
			mutation.done = true
			return affected, err
		})
		for i := len(eu.hooks) - 1; i >= 0; i-- {
			if eu.hooks[i] == nil {
				return 0, fmt.Errorf("do: uninitialized hook (forgotten import do/runtime?)")
			}
			mut = eu.hooks[i](mut)
		}
		if _, err := mut.Mutate(ctx, eu.mutation); err != nil {
			return 0, err
		}
	}
	return affected, err
}

// SaveX is like Save, but panics if an error occurs.
func (eu *EventUpdate) SaveX(ctx context.Context) int {
	affected, err := eu.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (eu *EventUpdate) Exec(ctx context.Context) error {
	_, err := eu.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (eu *EventUpdate) ExecX(ctx context.Context) {
	if err := eu.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (eu *EventUpdate) check() error {
	if v, ok := eu.mutation.AggregateID(); ok {
		if err := event.AggregateIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`do: validator failed for field "Event.aggregate_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.OrgID(); ok {
		if err := event.OrgIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`do: validator failed for field "Event.org_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.InstanceID(); ok {
		if err := event.InstanceIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`do: validator failed for field "Event.instance_id": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Version(); ok {
		if err := event.VersionValidator(string(v)); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`do: validator failed for field "Event.version": %w`, err)}
		}
	}
	if v, ok := eu.mutation.Creator(); ok {
		if err := event.CreatorValidator(string(v)); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`do: validator failed for field "Event.creator": %w`, err)}
		}
	}
	return nil
}

func (eu *EventUpdate) sqlSave(ctx context.Context) (n int, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   event.Table,
			Columns: event.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: event.FieldID,
			},
		},
	}
	if ps := eu.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := eu.mutation.AggregateID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldAggregateID,
		})
	}
	if value, ok := eu.mutation.OrgID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldOrgID,
		})
	}
	if value, ok := eu.mutation.InstanceID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldInstanceID,
		})
	}
	if value, ok := eu.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldVersion,
		})
	}
	if value, ok := eu.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldCreator,
		})
	}
	if eu.mutation.MetadataCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: event.FieldMetadata,
		})
	}
	if eu.mutation.DataCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: event.FieldData,
		})
	}
	if n, err = sqlgraph.UpdateNodes(ctx, eu.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	return n, nil
}

// EventUpdateOne is the builder for updating a single Event entity.
type EventUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *EventMutation
}

// SetAggregateID sets the "aggregate_id" field.
func (euo *EventUpdateOne) SetAggregateID(t types.UUID) *EventUpdateOne {
	euo.mutation.SetAggregateID(t)
	return euo
}

// SetOrgID sets the "org_id" field.
func (euo *EventUpdateOne) SetOrgID(t types.UUID) *EventUpdateOne {
	euo.mutation.SetOrgID(t)
	return euo
}

// SetInstanceID sets the "instance_id" field.
func (euo *EventUpdateOne) SetInstanceID(t types.UUID) *EventUpdateOne {
	euo.mutation.SetInstanceID(t)
	return euo
}

// SetVersion sets the "version" field.
func (euo *EventUpdateOne) SetVersion(t types.Version) *EventUpdateOne {
	euo.mutation.SetVersion(t)
	return euo
}

// SetCreator sets the "creator" field.
func (euo *EventUpdateOne) SetCreator(t types.UUID) *EventUpdateOne {
	euo.mutation.SetCreator(t)
	return euo
}

// Mutation returns the EventMutation object of the builder.
func (euo *EventUpdateOne) Mutation() *EventMutation {
	return euo.mutation
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (euo *EventUpdateOne) Select(field string, fields ...string) *EventUpdateOne {
	euo.fields = append([]string{field}, fields...)
	return euo
}

// Save executes the query and returns the updated Event entity.
func (euo *EventUpdateOne) Save(ctx context.Context) (*Event, error) {
	var (
		err  error
		node *Event
	)
	if len(euo.hooks) == 0 {
		if err = euo.check(); err != nil {
			return nil, err
		}
		node, err = euo.sqlSave(ctx)
	} else {
		var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
			mutation, ok := m.(*EventMutation)
			if !ok {
				return nil, fmt.Errorf("unexpected mutation type %T", m)
			}
			if err = euo.check(); err != nil {
				return nil, err
			}
			euo.mutation = mutation
			node, err = euo.sqlSave(ctx)
			mutation.done = true
			return node, err
		})
		for i := len(euo.hooks) - 1; i >= 0; i-- {
			if euo.hooks[i] == nil {
				return nil, fmt.Errorf("do: uninitialized hook (forgotten import do/runtime?)")
			}
			mut = euo.hooks[i](mut)
		}
		v, err := mut.Mutate(ctx, euo.mutation)
		if err != nil {
			return nil, err
		}
		nv, ok := v.(*Event)
		if !ok {
			return nil, fmt.Errorf("unexpected node type %T returned from EventMutation", v)
		}
		node = nv
	}
	return node, err
}

// SaveX is like Save, but panics if an error occurs.
func (euo *EventUpdateOne) SaveX(ctx context.Context) *Event {
	node, err := euo.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (euo *EventUpdateOne) Exec(ctx context.Context) error {
	_, err := euo.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (euo *EventUpdateOne) ExecX(ctx context.Context) {
	if err := euo.Exec(ctx); err != nil {
		panic(err)
	}
}

// check runs all checks and user-defined validators on the builder.
func (euo *EventUpdateOne) check() error {
	if v, ok := euo.mutation.AggregateID(); ok {
		if err := event.AggregateIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "aggregate_id", err: fmt.Errorf(`do: validator failed for field "Event.aggregate_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.OrgID(); ok {
		if err := event.OrgIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "org_id", err: fmt.Errorf(`do: validator failed for field "Event.org_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.InstanceID(); ok {
		if err := event.InstanceIDValidator(string(v)); err != nil {
			return &ValidationError{Name: "instance_id", err: fmt.Errorf(`do: validator failed for field "Event.instance_id": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Version(); ok {
		if err := event.VersionValidator(string(v)); err != nil {
			return &ValidationError{Name: "version", err: fmt.Errorf(`do: validator failed for field "Event.version": %w`, err)}
		}
	}
	if v, ok := euo.mutation.Creator(); ok {
		if err := event.CreatorValidator(string(v)); err != nil {
			return &ValidationError{Name: "creator", err: fmt.Errorf(`do: validator failed for field "Event.creator": %w`, err)}
		}
	}
	return nil
}

func (euo *EventUpdateOne) sqlSave(ctx context.Context) (_node *Event, err error) {
	_spec := &sqlgraph.UpdateSpec{
		Node: &sqlgraph.NodeSpec{
			Table:   event.Table,
			Columns: event.Columns,
			ID: &sqlgraph.FieldSpec{
				Type:   field.TypeString,
				Column: event.FieldID,
			},
		},
	}
	id, ok := euo.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`do: missing "Event.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := euo.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, event.FieldID)
		for _, f := range fields {
			if !event.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("do: invalid field %q for query", f)}
			}
			if f != event.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := euo.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := euo.mutation.AggregateID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldAggregateID,
		})
	}
	if value, ok := euo.mutation.OrgID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldOrgID,
		})
	}
	if value, ok := euo.mutation.InstanceID(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldInstanceID,
		})
	}
	if value, ok := euo.mutation.Version(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldVersion,
		})
	}
	if value, ok := euo.mutation.Creator(); ok {
		_spec.Fields.Set = append(_spec.Fields.Set, &sqlgraph.FieldSpec{
			Type:   field.TypeString,
			Value:  value,
			Column: event.FieldCreator,
		})
	}
	if euo.mutation.MetadataCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: event.FieldMetadata,
		})
	}
	if euo.mutation.DataCleared() {
		_spec.Fields.Clear = append(_spec.Fields.Clear, &sqlgraph.FieldSpec{
			Type:   field.TypeBytes,
			Column: event.FieldData,
		})
	}
	_node = &Event{config: euo.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, euo.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{event.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	return _node, nil
}
