//go:build !ignore_autogenerated
// +build !ignore_autogenerated

/*
Copyright The Gen Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by setter-gen. DO NOT EDIT.

package do

import (
	time "time"

	do "github.com/galaxyobe/go-ddd/pkg/domain/database/do"
	vo "github.com/galaxyobe/go-ddd/pkg/domain/eventsouring/vo"
	types "github.com/galaxyobe/go-ddd/pkg/types"
)

func (e *Event) SetConfig(val config) *Event {
	e.config = val
	return e
}

func (e *Event) SetId(val types.UUID) *Event {
	e.ID = val
	return e
}

func (e *Event) SetAggregateID(val types.UUID) *Event {
	e.AggregateID = val
	return e
}

func (e *Event) SetOrgID(val types.UUID) *Event {
	e.OrgID = val
	return e
}

func (e *Event) SetInstanceID(val types.UUID) *Event {
	e.InstanceID = val
	return e
}

func (e *Event) SetVersion(val types.Version) *Event {
	e.Version = val
	return e
}

func (e *Event) SetCreator(val types.UUID) *Event {
	e.Creator = val
	return e
}

func (e *Event) SetType(val vo.EventType) *Event {
	e.Type = val
	return e
}

func (e *Event) SetAggregateType(val vo.AggregateType) *Event {
	e.AggregateType = val
	return e
}

func (e *Event) SetMetadata(val do.StringMap) *Event {
	e.Metadata = val
	return e
}

func (e *Event) SetData(val []byte) *Event {
	e.Data = val
	return e
}

func (e *Event) SetSequence(val uint64) *Event {
	e.Sequence = val
	return e
}

func (e *Event) SetPreviousAggregateSequence(val uint64) *Event {
	e.PreviousAggregateSequence = val
	return e
}

func (e *Event) SetPreviousAggregateTypeSequence(val uint64) *Event {
	e.PreviousAggregateTypeSequence = val
	return e
}

func (e *Event) SetService(val string) *Event {
	e.Service = val
	return e
}

func (e *Event) SetCreateTime(val time.Time) *Event {
	e.CreateTime = val
	return e
}
